# Generated by Django 3.2.9 on 2022-05-28 16:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210710_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='value',
            field=models.CharField(help_text='Телефон для связи с клиникой', max_length=100),
        ),
        migrations.AlterField(
            model_name='doctorreview',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 28, 19, 18, 54, 999777)),
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 28, 19, 18, 54, 999777)),
        ),
        migrations.AlterField(
            model_name='servicereview',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 28, 19, 18, 54, 999777)),
        ),
    ]
